[package]
name = "bypass4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.5"
rand = "0.8.5"

build = { path = "build" }

# lib = { path = "../lib" }